version: 1.0.{build}
configuration: Release

install:
  - npm install npm@3.10.8 -g
  - set PATH=%APPDATA%\npm;src\node_modules\.bin;%PATH%
  - npm --version
  - cd src && npm install

build:
  verbosity: minimal

build_script:
  - nuget restore -verbosity quiet
  - test\aspnet_compiler -p src -v -u output
  - cd src && gulp

test_script:
  - ps: .\test\test.ps1
